name: 1.0$(rev:.r)

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    npm run test-ci
  displayName: 'npm test'

- task: PublishTestResults@1
  inputs:
    testResultsFiles: 'dist/__tests__/test-results.xml'

- task: CopyFiles@2
  displayName: 'Copy dist files'
  inputs:
    SourceFolder: 'dist/src'
    Contents: |
     **/*.js
     **/*.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/node-insult_$(Build.BuildNumber).zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/node-insult_$(Build.BuildNumber).zip'
